### ISSUE TITLE
Referencias Arquivos no diretorio public

### ISSUE THREAD

**Issue by joaovian06** [henrique5in/donorsbank#1]
As referencias dos  arquivos style.css, script.js e logo.png estão com o caminho faltando referencia a pasta public.

**Comment by henrique5in** [comment]
No arquivo server.js a configuração indicando o caminho para esses arquivos está em:
//Configuração de arquivos estáticos(extras)
server.use(express.static('public'))
Você provavelmente abriu o index sem inicializar o node. Depois de inicializado a página vai aparecer com o CSS aplicado.
